### ISSUE TITLE
Создание запросов для получения данных для графиков

### ISSUE THREAD

**Issue by Zhdanov-Dmitrii** [timetable-analytics/backend#18]
Входные параметры:
- Список id таблицы Event
- Параметр группировки по дате: день, месяц, год
- Параметр группировки по объекту: здание, аудитория, ФИО преподавателя, название дисциплины, учебная группа.

Реализовать запрос, возвращающий таблицу, содержащую кол-во пар, название объекта (аудитории, ФИО и т.д.), временной промежуток. Можно реализовать в 1 запросе занеся вариации в комментарии.

**Comment by Anastasia-Petrukhanova** [comment]
- [ ] Запрос для получения данных для графика по аудитории (адрес + название аудитории)
- [ ] Запрос для получения данных для графика по преподавателям
- [ ] Запрос для получения данных для графика по дисциплине
- [ ] Запрос для получения данных для графика по учебной группе
